/*
 * File: app/view/fromList.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.fromList', {
    extend: 'Ext.form.Panel',
    alias: 'widget.fromList',

    height: 502,
    id: 'fromList',
    width: 733,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    id: 'bankacc',
                    fieldLabel: 'Bank Account',
                    name: 'BankAccount',
                    displayField: 'name',
                    store: 'bankAccStore',
                    valueField: 'name'
                },
                {
                    xtype: 'datefield',
                    id: 'date',
                    fieldLabel: 'Date',
                    name: 'Date'
                },
                {
                    xtype: 'textfield',
                    id: 'depno',
                    fieldLabel: 'DepNO',
                    name: 'Dep_no'
                },
                {
                    xtype: 'combobox',
                    id: 'type',
                    fieldLabel: 'Type',
                    name: 'Type',
                    displayField: 'nameType',
                    store: 'typeAmountStore',
                    valueField: 'nameType'
                },
                {
                    xtype: 'textfield',
                    id: 'amount',
                    fieldLabel: 'Amount',
                    name: 'Amount'
                },
                {
                    xtype: 'textfield',
                    id: 'matchno',
                    fieldLabel: 'MatchNO',
                    name: 'Mach_no'
                },
                {
                    xtype: 'button',
                    id: 'add',
                    text: 'Add'
                }
            ]
        });

        me.callParent(arguments);
    }

});