/*
 * File: app/view/window.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.window', {
    extend: 'Ext.window.Window',
    alias: 'widget.Window',

    height: 383,
    id: 'window',
    width: 361,
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    id: 'BankAccount',
                    fieldLabel: 'Bank Accunt',
                    displayField: 'name',
                    store: 'bankAccStore'
                },
                {
                    xtype: 'datefield',
                    id: 'Date',
                    fieldLabel: 'Date'
                },
                {
                    xtype: 'textfield',
                    id: 'Dep_no',
                    fieldLabel: 'Dep NO'
                },
                {
                    xtype: 'combobox',
                    id: 'Type',
                    fieldLabel: 'Type',
                    displayField: 'nameType',
                    store: 'typeAmountStore'
                },
                {
                    xtype: 'textfield',
                    id: 'Mach_no',
                    fieldLabel: 'Match NO'
                },
                {
                    xtype: 'textfield',
                    id: 'Amount',
                    fieldLabel: 'Amount'
                },
                {
                    xtype: 'button',
                    id: 'Save',
                    width: 43,
                    text: 'save'
                },
                {
                    xtype: 'button',
                    id: 'Closed',
                    text: 'Closed'
                }
            ]
        });

        me.callParent(arguments);
    }

});