/*
 * File: app/model/banklist.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.banklist', {
    extend: 'Ext.data.Model',
    alias: 'model.banklist',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'BankAccount'
        },
        {
            name: 'Date'
        },
        {
            name: 'Dep_no'
        },
        {
            name: 'Withdrawal'
        },
        {
            name: 'Deposit'
        },
        {
            name: 'Mach_no'
        },
        {
            name: 'Member_id'
        },
        {
            name: 'Transaction_no'
        }
    ]
});