/*
 * File: app/view/gitpanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.gitpanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.gitpanel',

    height: 250,
    width: 754,
    title: 'My Grid Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Bank Account'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Time'
                },
                {
                    xtype: 'numbercolumn',
                    text: 'Dep_no'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Withdrawal'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Deposit'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'mach_no'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Member_id'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Transaction_no'
                }
            ]
        });

        me.callParent(arguments);
    }

});