/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    height: 502,
    width: 733,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    fieldLabel: 'Bank Account',
                    displayField: 'name',
                    store: 'bankStore',
                    valueField: 'id'
                },
                {
                    xtype: 'datefield',
                    fieldLabel: 'Date'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'DepNO'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Withdrawal'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'MatchNO'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Amount'
                },
                {
                    xtype: 'button',
                    text: 'Add'
                }
            ]
        });

        me.callParent(arguments);
    }

});